name: Deploy to EC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Clone repository on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'git clone https://github.com/minh261002/iTech.git /var/www/html/ || (cd /var/www/html/iTech && git pull)'

      - name: Install Composer dependencies
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'cd /var/www/html/iTech && composer install --no-interaction --prefer-dist --optimize-autoloader'

      - name: Run Laravel commands
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'cd /var/www/html/iTech && php artisan migrate --force && php artisan config:cache && php artisan route:cache'

      - name: Clear SSH key
        run: rm ~/.ssh/id_rsa
